name: Pulse Daily Summary Bot

on:
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: |
          python bot.py

      - name: Upload Summary
        uses: actions/upload-artifact@v4

        with:
          name: daily-summary
          path: daily_summary.txt
